opt_in_rules: # some rules are only opt-in
  - empty_count
included: # paths to include during linting. `--path` is ignored if present.
  - Sources
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
function_parameter_count:
   ignores_default_parameters: true
   warning: 7
