# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  test_xcode:
    macos:
      xcode: "10.1.0"
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    steps:
      - checkout
      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_DEVICES: "iPhone XS"
            SCAN_SCHEME: Skribent
            SCAN_PROJECT: "Skribent.xcodeproj"

      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs

  test_swift_package_manager:
    macos:
      xcode: "10.1.0"
    steps:
      - checkout
      - run: swift test --parallel

workflows:
  version: 2
  workflow:
    jobs:
      - test_xcode
      - test_swift_package_manager
